version: 2.0
jobs:
 build:
  docker:
   - image: alpine:3.7
  steps:
   - checkout
   - run:
      name: 最初の一歩
      command: |
       echo 'Hello Wirld'
       echo 'This is the delivery pipeline'
   - run:
      name: コードの取得
      command: |
       ls -alR
       echo '^^^That should look familiar^^^'
