version: 2.0
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello-World
          command: |
            echo 'Hello World'
            echo 'This is the delevry pipeline'
  I-Have-Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: コード取得
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: ノードを持つコンテナで実行
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: 承認の完了
          commnd: |
            echo 'Do work once the approval compted'

workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Hello-World
      - I-Have-Code:
          requires:
            - Hello-World
      - Run-With-Node:
          requires:
            - Hello-World
#      - Hold-For-Approval:
#          type: approval
#          requires:
#            - Hello-World
#            - I-Have-Code
      - Now-Complete:
          requires:
            - Hello-World
            - I-Have-Code
#           - Hold-For-Approval
